### Reconstructions LSTM Autoencoder

In [3]:

# lstm autoencoder recreate sequence
from numpy import array
from keras.models import Sequential
from keras.layers import LSTM
from keras.layers import Dense
from keras.layers import RepeatVector
from keras.layers import TimeDistributed
from keras.utils import plot_model

# define input sequence
sequence = array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])
# reshape input into [samples, timesteps, features]
n_in = len(sequence)
sequence = sequence.reshape((1, n_in, 1))
# define model
model = Sequential()
model.add(LSTM(100, activation='relu', input_shape=(n_in,1)))
model.add(RepeatVector(n_in))
model.add(LSTM(100, activation='relu', return_sequences=True))
model.add(TimeDistributed(Dense(1)))
model.compile(optimizer='adam', loss='mse')
# fit model
model.fit(sequence, sequence, epochs=300, verbose=0)
model.summary()# demonstrate recreation
yhat = model.predict(sequence, verbose=0)
print(yhat[0,:,0])

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_4 (LSTM)                (None, 100)               40800     
_________________________________________________________________
repeat_vector_2 (RepeatVecto (None, 9, 100)            0         
_________________________________________________________________
lstm_5 (LSTM)                (None, 9, 100)            80400     
_________________________________________________________________
time_distributed_2 (TimeDist (None, 9, 1)              101       
Total params: 121,301
Trainable params: 121,301
Non-trainable params: 0
_________________________________________________________________
[0.11062296 0.20638636 0.30260974 0.39946944 0.49723363 0.5962577
 0.6966715  0.79908675 0.9042391 ]


### Prediction LSTM Autoencoders

In [4]:
from numpy import array
from keras.models import Sequential
from keras.layers import LSTM
from keras.layers import Dense
from keras.layers import RepeatVector
from keras.layers import TimeDistributed
from keras.utils import plot_model
# define input sequence
seq_in = array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])
# reshape input into [samples, timesteps, features]
n_in = len(seq_in)
seq_in = seq_in.reshape((1, n_in, 1))
# prepare output sequence
seq_out = seq_in[:, 1:, :]
n_out = n_in - 1
# define model
model = Sequential()
model.add(LSTM(100, activation='relu', input_shape=(n_in,1)))
model.add(RepeatVector(n_out))
model.add(LSTM(100, activation='relu', return_sequences=True))
model.add(TimeDistributed(Dense(1)))
model.compile(optimizer='adam', loss='mse')
plot_model(model, show_shapes=True, to_file='predict_lstm_autoencoder.png')
# fit model
model.fit(seq_in, seq_out, epochs=300, verbose=0)
# demonstrate prediction
yhat = model.predict(seq_in, verbose=0)
print(yhat[0,:,0])

('Failed to import pydot. You must `pip install pydot` and install graphviz (https://graphviz.gitlab.io/download/), ', 'for `pydotprint` to work.')
[0.16978964 0.29341868 0.40498853 0.5063768  0.6031685  0.69930184
 0.7977215  0.90121293]


### Composite LSTM Autoencoder

In [5]:
# lstm autoencoder reconstruct and predict sequence
from numpy import array
from keras.models import Model
from keras.layers import Input
from keras.layers import LSTM
from keras.layers import Dense
from keras.layers import RepeatVector
from keras.layers import TimeDistributed
from keras.utils import plot_model
# define input sequence
seq_in = array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])
# reshape input into [samples, timesteps, features]
n_in = len(seq_in)
seq_in = seq_in.reshape((1, n_in, 1))
# prepare output sequence
seq_out = seq_in[:, 1:, :]
n_out = n_in - 1
# define encoder
visible = Input(shape=(n_in,1))
encoder = LSTM(100, activation='relu')(visible)
# define reconstruct decoder
decoder1 = RepeatVector(n_in)(encoder)
decoder1 = LSTM(100, activation='relu', return_sequences=True)(decoder1)
decoder1 = TimeDistributed(Dense(1))(decoder1)
# define predict decoder
decoder2 = RepeatVector(n_out)(encoder)
decoder2 = LSTM(100, activation='relu', return_sequences=True)(decoder2)
decoder2 = TimeDistributed(Dense(1))(decoder2)
# tie it together
model = Model(inputs=visible, outputs=[decoder1, decoder2])
model.compile(optimizer='adam', loss='mse')
plot_model(model, show_shapes=True, to_file='composite_lstm_autoencoder.png')
# fit model
model.fit(seq_in, [seq_in,seq_out], epochs=300, verbose=0)
# demonstrate prediction
yhat = model.predict(seq_in, verbose=0)
print(yhat)

('Failed to import pydot. You must `pip install pydot` and install graphviz (https://graphviz.gitlab.io/download/), ', 'for `pydotprint` to work.')
[array([[[0.10243267],
        [0.1993747 ],
        [0.29919326],
        [0.39964893],
        [0.50004876],
        [0.6002997 ],
        [0.7003342 ],
        [0.8001249 ],
        [0.89969885]]], dtype=float32), array([[[0.16512783],
        [0.2889748 ],
        [0.402998  ],
        [0.50937825],
        [0.6102191 ],
        [0.7067359 ],
        [0.79991096],
        [0.8905692 ]]], dtype=float32)]


### Standalone LSTM Encoder

In [28]:
# lstm autoencoder recreate sequence
from numpy import array
from keras.models import Sequential
from keras.models import Model
from keras.layers import LSTM
from keras.layers import Dense
from keras.layers import RepeatVector
from keras.layers import TimeDistributed
from keras.utils import plot_model

'''
# define input sequence
sequence = array([[0.1, 0.2, 0.3], [0.4, 0.5, 0.6], [0.7, 0.8, 0.9]])
print(sequence.shape)
# reshape input into [samples, timesteps, features]
n_steps = 1
n_inputs = 3
n_features = 3
n_neurons = 10
'''

sequence = array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])
sequence2 = array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])


print(sequence.shape, len(sequence))
n_steps = 9
n_inputs = 1
n_features = 1
n_neurons = 5

sequence = sequence.reshape((n_inputs, n_steps, n_features))
print(sequence.shape)
# define model
model = Sequential()
model.add(LSTM(n_neurons, activation='relu', input_shape=(n_steps,n_features)))
model.add(RepeatVector(n_steps))
model.add(LSTM(n_neurons, activation='relu', return_sequences=True))
model.add(TimeDistributed(Dense(1)))
model.compile(optimizer='adam', loss='mse')
# fit model
model.fit(sequence, sequence, epochs=300, verbose=0)
model.summary()# demonstrate recreation
yhat = model.predict(sequence, verbose=0)
print(yhat[0,:,0])
# connect the encoder LSTM as the output layer
model = Model(inputs=model.inputs, outputs=model.layers[0].output)
model.summary()
# get the feature vector for the input sequence
yhat = model.predict(sequence2)
print(yhat.shape)
print(yhat)

(9,) 9
(1, 9, 1)
Model: "sequential_21"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_42 (LSTM)               (None, 5)                 140       
_________________________________________________________________
repeat_vector_21 (RepeatVect (None, 9, 5)              0         
_________________________________________________________________
lstm_43 (LSTM)               (None, 9, 5)              220       
_________________________________________________________________
time_distributed_21 (TimeDis (None, 9, 1)              6         
Total params: 366
Trainable params: 366
Non-trainable params: 0
_________________________________________________________________
[0.19158703 0.2660244  0.34132135 0.41904387 0.5007428  0.5881349
 0.6832156  0.7884127  0.9068068 ]
Model: "functional_37"
_________________________________________________________________
Layer (type)                 Output Shape     

### Denoising AutoEncoders

In [4]:
from autoencoder import DenoisingAutoencoder
from numpy import array


da = DenoisingAutoencoder(n_hidden=10)

X = array([[0.1, 0.2, 0.3], [0.4, 0.5, 0.6], [0.7, 0.8, 0.9]])

n_steps = 9
n_inputs = 1
n_features = 1
n_neurons = 5

X = X.reshape((3, 3))
print(X.shape)

da.fit(X)

new_X = da.transform(X)
print(new_X)

#To change the dimensionality of X (in this case, changed_X will have "n_hidden" features)

changed_X = da.transform_latent_representation(X)
print(changed_X)


(3, 3)
[[0.68590391 0.54090121 0.88470576]
 [0.7531608  0.72093559 0.94111915]
 [0.8011296  0.80879546 0.96230284]]
[[0.48111321 0.43956525 0.55430981 0.52468811 0.49056521 0.63360623
  0.42089127 0.30110503 0.6965202  0.57480749]
 [0.53730781 0.34092447 0.62362589 0.63221406 0.49147443 0.81327803
  0.31701471 0.13899075 0.79988807 0.6121095 ]
 [0.59257035 0.25437226 0.68822506 0.72802419 0.49238371 0.91645945
  0.22865267 0.05703552 0.87439698 0.64814221]]
